### ISSUE TITLE
Crud function for admin

### ISSUE THREAD

**Issue by DavidckPixel** [viakunst/mighty-eagle#2]
aswell as detailed read, needs to be added for admin users.

**Comment by IkNikNik** [comment]
- [ ] Create users
- [ ] Read users
   - [ ] Group
   - [ ] Individual
- [ ] Update users
- [ ] Delete users

Read: show all columns at first, do survey to find out which columns are useful, than only show needed columns

**Comment by IkNikNik** [comment]
ToDo:
convert UserPool.tsx to function component.

**Comment by mkrugr** [comment]
Userpool has been converted. CRUD functions added to master branch.
