### ISSUE TITLE
Make user pool configurable

### ISSUE THREAD

**Issue by jasperweyne** [viakunst/mighty-eagle#24]
Currently, a user needs to select the user pool to act upon in the admin panel. In practice, this is undesirable, as each user pool may be managed by different users. (eg. our testing pool should only be managed by the dev team). Therefore, a config to fix the management table to a single user pool would be desirable. This can be the same constant value as used by the login flow, or it can be split.

**Comment by mkrugr** [comment]
Added in admin config pull request.
