### ISSUE TITLE
Weird error messages when creating new account

### ISSUE THREAD

**Issue by jasperweyne** [viakunst/mighty-eagle#29]
When creating a new account through the admin interface, the system will report for example

- "Telephone number not long enough" when it's the incorrect length. However, this also happens if the telephone number length is in fact too long
- A telephone number must start with +316, however, a person from non-dutch origin might have a different cell phone number. Validation for a + only would be correct.
- When entering an email address, "'attributes[email]' is not a valid email" is an unfriendly error message.

**Comment by mkrugr** [comment]
Fixed telephone number validation messages. The e-mail message is a config parameter, under message.

**Comment by mkrugr** [comment]
Fixed in latest config and master build.
