### ISSUE TITLE
Fullname is not stored when creating new account

### ISSUE THREAD

**Issue by jasperweyne** [viakunst/mighty-eagle#31]
When creating a new account, the users first name and last name must be entered, and are stored in the database properly. However, the full name, consisting of a combined first and last name, is not stored. Therefore, the name for the new account in the admin user overview remains empty.

**Comment by mkrugr** [comment]
This is a config issue, compound field need to be added to the ADMIN_MUTATE field for the field to be recalculated and uploaded after a form submit.

**Comment by mkrugr** [comment]
Fixed in latest config.
