### ISSUE TITLE
Edit confirmation button should be renamed

### ISSUE THREAD

**Issue by jasperweyne** [viakunst/mighty-eagle#36]
Currently, when using mighty eagle, the system is localized in dutch. However, when confirming a new account or an account edit (both admin and profile), the confirmation buttons are localized in english. This should be consistent.

**Comment by mkrugr** [comment]
Fixed the names of the edit button. For the form confirmation, update is (arguably) dutch, reopen if this is too much of an issue. Currently I think it is fine.
