### ISSUE TITLE
Searchfield is broken

### ISSUE THREAD

**Issue by jasperweyne** [viakunst/mighty-eagle#37]
Currently, the search field does not seem to function properly. Moreover, its user-friendliness could be improved by not requiring the specification of the column to be searched.

**Comment by mkrugr** [comment]
Default column could be selected, but it still might be useful keep the possibility to switch search field.

**Comment by mkrugr** [comment]
I do acknowledge that the current search system is slighty broken

**Comment by jasperweyne** [comment]
Why is it necessary to specify a search field at all?

**Comment by mkrugr** [comment]
Use case for this function: Emails do not always contain the same names as have been given. 

For example, you receive an email from a request for information which has be signed by a person like this 
"Hello, I'd like some info. -J"
from the adress LuckyJ66@email.com. You now need to find this person in the list of users. This is easy if you can search on the email field. 

Another case, a person asks you directly in person for information, which you have to email to him/her. Now it is convient to find the user by the name field. 

Argument can be made to search on both these fields. And allowing to search on both requires specification of a search field.

**Comment by mkrugr** [comment]
Fixed the bugs regarding searches and use the default field option. It should be fine for now. Reopen if you think otherwise.
