### ISSUE TITLE
add relevative data columns for user

### ISSUE THREAD

**Issue by DavidckPixel** [viakunst/mighty-eagle#7]

**Comment by jasperweyne** [comment]
A 'ADMIN_OVERVIEW' context could be added to an ConfigContext. Note, however, that data retrieval works differently in tables. A reconsideration of the design of the view() method signature of an AttributeInstance may be necessary.

**Comment by mkrugr** [comment]
An ADMIN_OVERVIEW would not work for all fields as creation_date, status etc are field that are not attributes. A small comprise solution was added in admin config pull request.
